apiVersion: v1
kind: Secret
metadata:
  name: postgres-creds
data:
  password: cG9zdGdyZXM=  # base64 for "postgres"              
  database_uri: cG9zdGdyZXNxbCtwc3ljb3BnOi8vcG9zdGdyZXM6cG9zdGdyZXNAcG9zdGdyZXM6NTQzMi9wcm9kdWN0cw==
  # base64 for "postgresql+psycopg://postgres:postgres@postgres:5432/products"
