---
# Task: pylint
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Task","metadata":{"annotations":{"tekton.dev/categories":"Code Quality","tekton.dev/displayName":"pylint","tekton.dev/pipelines.minVersion":"0.17.0","tekton.dev/platforms":"linux/amd64,linux/s390x,linux/ppc64le","tekton.dev/tags":"python, pylint, poetry"},"labels":{"app.kubernetes.io/version":"0.4"},"name":"pylint","namespace":"luoashley-dev"},"spec":{"description":"Use to run pylint on the provided input source.  If Poetry or Pipenv is being used it will detect  the poetry.lock and Pipfile file and install using them.","params":[{"default":"quay.io/rofrano/python:3.11-slim","description":"The container image with pylint","name":"image"},{"default":".","description":"The path to the module which should be analyzed by pylint","name":"path","type":"string"},{"default":[],"description":"The arguments to pass to the pylint CLI.","name":"args","type":"array"},{"default":"requirements.txt","description":"The name of the requirements file inside the source location","name":"requirements-file"}],"steps":[{"args":["$(params.args)"],"image":"$(params.image)","name":"pylint","script":"#!/bin/bash\nset -e\nexport PATH=$PATH:$HOME/.local/bin:\n\necho \"***** Installing dependencies *****\"\nif [ -e \"poetry.lock\" ]; then\n  echo \"Found poetry.lock file: using poetry ...\"\n  python -m pip install --upgrade pip poetry\n  poetry config virtualenvs.create false\n  poetry install\nelif [ -e \"Pipfile\" ]; then\n  echo \"Found Pipfile file: using pipenv ...\"\n  python -m pip install --upgrade pip pipenv\n  pipenv install --system --dev\nelif [ -n \"$(params.requirements-file)\" ] \u0026\u0026 [ -e \"$(params.requirements-file)\" ]; then\n  python -m pip install --user -r \"$(params.requirements-file)\"\nfi\n\n# Make sure pylint is installed\npython -m pip install pylint\n\necho \"***** Running Linting *****\"\npylint $@ \"$(params.path)\"\n","workingDir":"$(workspaces.source.path)"}],"workspaces":[{"description":"The workspace with the source code.","name":"source"}]}}
    tekton.dev/categories: Code Quality
    tekton.dev/displayName: pylint
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/platforms: 'linux/amd64,linux/s390x,linux/ppc64le'
    tekton.dev/tags: 'python, pylint, poetry'
  resourceVersion: '6636109534'
  name: pylint
  uid: fd1d58fc-5f28-4341-98a3-db7f23fbef69
  creationTimestamp: '2025-11-13T00:43:23Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
            'f:tekton.dev/categories': {}
            'f:tekton.dev/displayName': {}
            'f:tekton.dev/pipelines.minVersion': {}
            'f:tekton.dev/platforms': {}
            'f:tekton.dev/tags': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/version': {}
        'f:spec':
          .: {}
          'f:description': {}
          'f:params': {}
          'f:steps': {}
          'f:workspaces': {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2025-11-13T00:43:23Z'
  namespace: luoashley-dev
  labels:
    app.kubernetes.io/version: '0.4'
spec:
  description: Use to run pylint on the provided input source.  If Poetry or Pipenv is being used it will detect  the poetry.lock and Pipfile file and install using them.
  params:
    - default: 'quay.io/rofrano/python:3.11-slim'
      description: The container image with pylint
      name: image
      type: string
    - default: .
      description: The path to the module which should be analyzed by pylint
      name: path
      type: string
    - default: []
      description: The arguments to pass to the pylint CLI.
      name: args
      type: array
    - default: requirements.txt
      description: The name of the requirements file inside the source location
      name: requirements-file
      type: string
  steps:
    - args:
        - $(params.args)
      computeResources: {}
      image: $(params.image)
      name: pylint
      script: |
        #!/bin/bash
        set -e
        export PATH=$PATH:$HOME/.local/bin:

        echo "***** Installing dependencies *****"
        if [ -e "poetry.lock" ]; then
          echo "Found poetry.lock file: using poetry ..."
          python -m pip install --upgrade pip poetry
          poetry config virtualenvs.create false
          poetry install
        elif [ -e "Pipfile" ]; then
          echo "Found Pipfile file: using pipenv ..."
          python -m pip install --upgrade pip pipenv
          pipenv install --system --dev
        elif [ -n "$(params.requirements-file)" ] && [ -e "$(params.requirements-file)" ]; then
          python -m pip install --user -r "$(params.requirements-file)"
        fi

        # Make sure pylint is installed
        python -m pip install pylint

        echo "***** Running Linting *****"
        pylint $@ "$(params.path)"
      workingDir: $(workspaces.source.path)
  workspaces:
    - description: The workspace with the source code.
      name: source
# Task: pytest-env
apiVersion: tekton.dev/v1
kind: Task
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Task","metadata":{"annotations":{"tekton.dev/categories":"Testing","tekton.dev/displayName":"pytest tests","tekton.dev/pipelines.minVersion":"0.17.0","tekton.dev/platforms":"linux/amd64,linux/s390x,linux/ppc64le","tekton.dev/tags":"python, pytest"},"labels":{"app.kubernetes.io/version":"0.1"},"name":"pytest-env","namespace":"luoashley-dev"},"spec":{"description":"This task can be used to perform unit tests with pytest. It supports both requirements.txt, Pipfile, \u0026 poetry.lock files.\nIt also has the ability to create an environment variable that is sourced from a Secret. This allows you to define credentials that can be used to connect to a test database.","params":[{"default":[],"description":"The arguments to pass to the pytest CLI.","name":"pytest-args","type":"array"},{"default":"postgres-creds","description":"The name of the secret containing a database_uri key","name":"secret-name","type":"string"},{"default":"database_uri","description":"The name of the key that contains the database uri","name":"secret-key","type":"string"}],"steps":[{"args":["$(params.pytest-args)"],"env":[{"name":"DATABASE_URI","valueFrom":{"secretKeyRef":{"key":"$(params.secret-key)","name":"$(params.secret-name)"}}}],"image":"quay.io/rofrano/python:3.11-slim","name":"pytest","script":"#!/bin/bash\nset -e\nexport PATH=$PATH:$HOME/.local/bin:\n\necho \"***** Installing dependencies *****\"\nif [ -e \"poetry.lock\" ]; then\n  echo \"Found poetry.lock file: using poetry ...\"\n  python -m pip install --upgrade pip poetry\n  poetry config virtualenvs.create false\n  poetry install\nelif [ -e \"Pipfile\" ]; then\n  echo \"Found Pipfile file: using pipenv ...\"\n  python -m pip install --upgrade pip pipenv\n  pipenv install --system --dev\nelif -e \"requirements.txt\" ]; then\n  python -m pip install --user -r requirements.txt\nfi\n\n# Make sure pylint is installed\npython -m pip install pytest\n\necho \"***** Running Tests *****\"\npytest --version\npytest\n","workingDir":"$(workspaces.source.path)"}],"workspaces":[{"name":"source"}]}}
    tekton.dev/categories: Testing
    tekton.dev/displayName: pytest tests
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/platforms: 'linux/amd64,linux/s390x,linux/ppc64le'
    tekton.dev/tags: 'python, pytest'
  resourceVersion: '6636109568'
  name: pytest-env
  uid: 1f90213d-47df-4a1b-a1cc-5db74b61560e
  creationTimestamp: '2025-11-13T00:43:23Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
            'f:tekton.dev/categories': {}
            'f:tekton.dev/displayName': {}
            'f:tekton.dev/pipelines.minVersion': {}
            'f:tekton.dev/platforms': {}
            'f:tekton.dev/tags': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/version': {}
        'f:spec':
          .: {}
          'f:description': {}
          'f:params': {}
          'f:steps': {}
          'f:workspaces': {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2025-11-13T00:43:23Z'
  namespace: luoashley-dev
  labels:
    app.kubernetes.io/version: '0.1'
spec:
  description: |-
    This task can be used to perform unit tests with pytest. It supports both requirements.txt, Pipfile, & poetry.lock files.
    It also has the ability to create an environment variable that is sourced from a Secret. This allows you to define credentials that can be used to connect to a test database.
  params:
    - default: []
      description: The arguments to pass to the pytest CLI.
      name: pytest-args
      type: array
    - default: postgres-creds
      description: The name of the secret containing a database_uri key
      name: secret-name
      type: string
    - default: database_uri
      description: The name of the key that contains the database uri
      name: secret-key
      type: string
  steps:
    - args:
        - $(params.pytest-args)
      computeResources: {}
      env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              key: $(params.secret-key)
              name: $(params.secret-name)
      image: 'quay.io/rofrano/python:3.11-slim'
      name: pytest
      script: |
        #!/bin/bash
        set -e
        export PATH=$PATH:$HOME/.local/bin:

        echo "***** Installing dependencies *****"
        if [ -e "poetry.lock" ]; then
          echo "Found poetry.lock file: using poetry ..."
          python -m pip install --upgrade pip poetry
          poetry config virtualenvs.create false
          poetry install
        elif [ -e "Pipfile" ]; then
          echo "Found Pipfile file: using pipenv ..."
          python -m pip install --upgrade pip pipenv
          pipenv install --system --dev
        elif -e "requirements.txt" ]; then
          python -m pip install --user -r requirements.txt
        fi

        # Make sure pylint is installed
        python -m pip install pytest

        echo "***** Running Tests *****"
        pytest --version
        pytest
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
