name: CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    # Required services    
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis:6-alpine
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
            
      - name: Install Python package dependencies
        run: |
          python -m pip install -U pip pipenv
          pipenv install --system --dev

      - name: Run linting by preset Makefile
        run: |
          make lint
          
      - name: Run testing by preset Makefile
        run: |
          make test

      - name: Install packages for Codecov to work
        run: apt-get update && apt-get install -y git curl gpg
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: CSCI-GA-2820-FA25-003/products
