name: CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    # Required services    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: products_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
            
      - name: Install OS deps
        run: |
          apt-get update
          apt-get install -y make git curl gpg build-essential gcc
          
      - name: Install pipenv
        run: python -m pip install -U pip pipenv
          
      - name: Install Python deps
        run: |
          pipenv install --system --dev

      - name: Run linting by preset Makefile
        run: |
          make lint
          
      - name: Run testing by preset Makefile
        run: |
          make test

      - name: Install packages for Codecov to work
        run: apt-get update && apt-get install -y git curl gpg
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: CSCI-GA-2820-FA25-003/products
