name: CI - Run Tests

on:
  pull_request:
  push:
    branches: [ main ]

env:
  DATABASE_URI: "sqlite:///:memory:"  
  FLASK_ENV: "development"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make test

